requirements = ["Binary"]

allowed_blocks = ["Boolean"]

[[chapter]]
title = "Half Adder"

inputs = ["a", "b"]
outputs = ["sum", "carry"]

[chapter.truth_table]
format = "$a + $b = $carry$sum"
function = "HalfAdder"

[[chapter]]
title = "Full Adder"
allowed_blocks = ["Add<InBundle=2, In=1, Out=2>"]

inputs = ["a", "b", "c"]
outputs = ["sum", "carry"]

[chapter.truth_table]
format = "$a + $b + $c = $carry$sum"
function = "FullAdder"

[[chapter]]
title = "Addition"
allowed_blocks = ["Add<InBundle=3, In=1, Out=2>"]

inputs = ["a[4]", "b[4]"]
outputs = "sum[5]"

[chapter.truth_table]
format = "$a + $b = $sum"
function = "Adder"

[[chapter]]
title = "Subtraction"
allowed_blocks = ["Add"]

inputs = ["a[4]", "b[4]"]
outputs = ["difference[4]", "sign"]

[chapter.truth_table]
format = "$a - $b = $sign $difference"
function = "Subtractor"



