[package]
name = "digolog_module_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
digolog_math.path = "../math"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
derive_more = "0.99.17"
anyhow = "1.0"
