color = "red"

[block.Add]
lable = "+"
input = "bundle<InBundle, In>"
output = "cable<Out> sum"

[block.Sub]
lable = "-"
input = ["cable", "cable sub"]
output = ["cable diff", "wire sign"]

[block.Mul]
lable = "x"
input = ["bundle<B, I>"]
output = "cable<P> prod"

[block.Div]
lable = "/"
input = ["cable<C>", "cable<D> divisor"]
output = "cable<R>"

[block.Mod]
lable = "mod"
input = ["cable<C>", "cable<D> divisor"]
output = "cable<R>"

