color = "orange"

[block.Multiplexer]
lable = "Mux"
input = ["bundle<B, C>", "cable<S> select"]
output = "cable<C>"
# constant.S = "B:bits()"

[block.Encoder]
lable = "Enc"
input = "bundle<B, 1>"
output = "cable<C>"
# constant.C = "B:bits()"

[block.Decoder]
lable = "Dec"
input = "cable<C>"
output = "bundle<B, 1>"
constant.C = "B:bits()"

[block.CopyWire]
lable = "Copy"
input = "wire"
output = "cable"

[block.CopyCable]
lable = "Copy"
input = "cable<C>"
output = "bundle<B, C>"

[block.Clock]
lable = "Clock"
output = "wire"
