[package]
name = "digolog_math"
version = "0.1.0"
edition = "2021"

[dependencies.derive_more]
version = "0.99.17"

[dependencies.bytemuck]
version = "1.15.0"
features = ["derive", "nightly_portable_simd"]
